---
spring:
  application:
    name: coe-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranajit-jana/coe-spring-config.git
          #searchPaths: coe-spring-config
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8888